# Generated by Django 5.0.4 on 2024-05-24 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("p1App", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectdb",
            name="date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="projectdb",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="projectdb",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="project_files"),
        ),
        migrations.AlterField(
            model_name="projectupdatedb",
            name="project_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="p1App.projectdb",
            ),
        ),
    ]
