# Generated by Django 4.1.5 on 2024-05-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1App', '0002_projectdb_date_projectdb_end_date_projectdb_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserdb',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuserdb',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuserdb',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuserdb',
            name='instagram',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
