# Generated by Django 4.1.5 on 2024-05-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1App', '0003_customuserdb_address_customuserdb_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagedb',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
